### ISSUE TITLE
root get detected on yono sbi banking app and movieshub apk. super user not allowed.

### ISSUE THREAD

**Issue by spidy2356** [tiann/KernelSU#1357] opened 2024-02-12 15:30 UTC
### Please check before submitting an issue

- [X] I have searched the issues and haven't found anything relevant
- [X] I will upload bugreport file in KernelSU Manager - Settings - Report log
- [X] I know how to reproduce the issue which may not be specific to my device

### Describe the bug

[yono sbi](https://play.google.com/store/apps/details?id=com.sbi.lotusintouch&hl=en&gl=US) banking app get starting crash after get new update and [movieshub](https://movieshubapk.com/) app detect root on app startup.

edit: yono sbi banking app crash fixed after flash [shamiko ](https://github.com/LSPosed/LSPosed.github.io/releases)

### To Reproduce

1. yono sbi banking app: crash on startup
2. movieshub app: detect root on start up even after no super user granted.

### Expected behavior

not get crash or detect root as they are not allowed as super user.

### Screenshots

![Screenshot_20240212-203920_MOVIES HUB](https://github.com/tiann/KernelSU/assets/101243689/d2aecebd-d757-4c6f-aedf-140dcd622d3e)

### Logs

[KernelSU_bugreport_2024-02-12_20_41.tar.gz](https://github.com/tiann/KernelSU/files/14240072/KernelSU_bugreport_2024-02-12_20_41.tar.gz)

### Device info

- Device: poco x2 (phoenix)
- OS Version: android 13
- KernelSU Version: v0.7.6 (11458)
- Kernel Version: 4.14.326-Alza-v2.2
![Screenshot_20240212-210025_KernelSU](https://github.com/tiann/KernelSU/assets/101243689/80f76e5a-7783-4986-8615-ed300739c3b3)

**Comment by meiser79** [comment] 2024-02-12 19:57
Might be a duplicate of #1328. You should try a kernel with latest kernelsu git (11508) and CI version of manager app (11509).

**Comment by tiann** [comment] 2024-02-17 03:17
#1328

**Closed by tiann** 2024-02-17 03:17 UTC
